### ISSUE TITLE
Omeka integration mentions Failed records when added to Omeka

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#1]
The integration report says ‘Failed Records: 59’, yet the 59 records have been added to Omeka. 

Set Name: hond, Total Records: 59
Valid Records: 59, Invalid Records: 0
Added Records: 0, Updated Records: 0, Failed Records: 59

**Comment by roxannewyns** [comment]
also in case of updated records, the Omeka integration report gives this result though the update worked fine.

Set Name: hond, Total Records: 59
Valid Records: 59, Invalid Records: 0

## Added Records: 0, Updated Records: 0, Failed Records: 59

**Comment by naeemmuhammad** [comment]
This situation occurs when solr is not running. Omeka performs the required operation successfully even if solr is not running but returns error in response to the rest api calls. Solution perhaps is to make sure that solr is running before we start integration.
