### ISSUE TITLE
HTML in metadata

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#11]
assigned @naeemmuhammad 

cc @samalloing 

CAG uses the HTML editor for certain field in CollectiveAccess.
![hvl](https://cloud.githubusercontent.com/assets/3798589/6526766/988d48c2-c415-11e4-8420-369bc326679e.png)

When this data is synced to Omeka, it is imported as followed:
![capture](https://cloud.githubusercontent.com/assets/3798589/6526787/bebc101e-c415-11e4-864e-67cfd6472a7e.JPG)

And appears in the Front end as
![capture](https://cloud.githubusercontent.com/assets/3798589/6526826/ff275b86-c415-11e4-8f2e-4fce128c3c91.JPG)

When HTML is toggle checked, it appears correctly in the front-end
![capture](https://cloud.githubusercontent.com/assets/3798589/6526881/8eb42f4a-c416-11e4-9872-afe02feb4d5d.JPG)

![capture](https://cloud.githubusercontent.com/assets/3798589/6526875/779f8eee-c416-11e4-9563-f36c6fd3a500.JPG)

**Comment by naeemmuhammad** [comment]
https://github.com/libis/euInside/commit/3be5f5307c4ec340c349292977867cb7e195f89a
