### ISSUE TITLE
digitool and georeference not added for exportHVL_actoren

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#12]
assigned @naeemmuhammad 

For the new records, digitool and georeference (map) info isn't added
In Omeka
/items/edit/id/60510

For these new ones just added, the georeference is added, but not the digitool image
/items/edit/id/61698
/items/edit/id/61704
/items/edit/id/61701

I also deleted one image (from 3 to 2 image) + changed the georeference to "Gent" for this CollectieveAcces item "/EntityEditor/Edit/entity_id/301"
In Omeka this item "/items/edit/id/60435" the digitool and map info isn't updated.

**Comment by naeemmuhammad** [comment]
Fix for georeference issue: https://github.com/libis/libisinworker/commit/b0c198440e6b5021b55035d6820fe2068af99ec2

Digitool related issue needs some additional support in the Digitool plugin. Actually, we need to remove images of an item before adding new images, this is currently not possible. I have created another issue (https://github.com/libis/libisin/issues/13) for this.
