### ISSUE TITLE
values are split up on ' when imported

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#15]
assigned @naeemmuhammad 

Vander Vaeren, Julien, Le livre d'or de l'agriculture belge, Thill, Bruxelles, 1939 is split up on the ' and put into different fields. 

Cfr.CollectiveAccess object_id/31455 ; Omeka /id/64434 

![capture](https://cloud.githubusercontent.com/assets/3798589/7812793/e8af57fc-03b5-11e5-9e1b-9b9d76a1a5f1.JPG)

![capture2](https://cloud.githubusercontent.com/assets/3798589/7812792/e8aac606-03b5-11e5-99a0-503be712fd6f.JPG)

**Comment by roxannewyns** [comment]
perhaps this also happens on other characters (" or - ...)? You should check this.

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/euInside/commit/802ca211118ca08a211f443f2d66d240a0d6306f
