### ISSUE TITLE
change Set name to Set code

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#2]
It' the set code you're searching on, not the set name. This makes it confusing for the user, so better change the name. It might also be useful to add a search on set name perhaps?

![capture1](https://cloud.githubusercontent.com/assets/3798589/5706391/dae8f20c-9a80-11e4-984b-fa71f99bb330.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/5706390/dae4f24c-9a80-11e4-873b-0cb765529e0d.JPG)

**Comment by naeemmuhammad** [comment]
b27d34eed9ffc08fbaef54eeec556b36f7b7ac02
