### ISSUE TITLE
add mapping function for Split

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#5]
Currently when you use the mapping rule 'Split', the second half of the value after the split is placed in a second field. 
Provide Split function that ignores all text after the split.

E.g. CollectiveAccess exports the spatial coverage as follows "Gent - 9000 [Gent - 9000]"
We only need "Gent - 9000". I want to be able to split on  "[", and everything after [ can be dropped and doesn't have to be imported.
Or perhaps we only need "Gent". Then split on "-" and everything after - can be dropped and doesn't have to be imported.

**Comment by naeemmuhammad** [comment]
This currently works if we supply only one output field. For example:
ca_abc = Gent - 9000 [Gent - 9000]
A    SPLIT,ca_abc,[,dc:abc  
Command A will split values into 'Gent - 9000' and 'Gent - 9000]'. First part of the split will go to the first output field (dc:abc). The second part of the split will only be used if there is second output field.

B  SPLIT,ca_abc,-,dc:abc  
Command B will copy value 'Gent' to dc:abc.
