### ISSUE TITLE
when multiple values in CA export, repeat Omeka field

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#7]
When multiple values are exported for the same element, this must be put in a repeated field in Omeka.
Multiple values are separated by a pipe in the CA export. 
In Omeka you can repeat each field (green box "invoer toevoegen"), so each string should go in a repeated field instead of on one line as is the case now.   

![capture1](https://cloud.githubusercontent.com/assets/3798589/6106098/a89f438e-b05e-11e4-8f46-211895fe609b.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/6106108/b7e7fe80-b05e-11e4-87ca-5c24030a813c.JPG)

**Comment by naeemmuhammad** [comment]
We use 'split' mapping command with one output field mentioned multiple times. However a new command (issue: https://github.com/libis/libisin/issues/10) will be added to the dmt service to implement this behaviour.
