### ISSUE TITLE
to many tags added

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#8]
In many cases, more tags are added then present. E.g. some examples below.
The tags don't come from the previous ingested item it appears. I did notice that it is often 'basis insteek', 'beroep', 'basisketen'...

![capture](https://cloud.githubusercontent.com/assets/3798589/6106489/237890da-b062-11e4-9f8f-eb736a67897f.JPG)
![capture3](https://cloud.githubusercontent.com/assets/3798589/6106475/fcac504a-b061-11e4-91e5-43426f019359.JPG)

![capture](https://cloud.githubusercontent.com/assets/3798589/6106496/39b0e492-b062-11e4-98d8-46177d93237b.JPG)
![capture2](https://cloud.githubusercontent.com/assets/3798589/6106477/fcb139d4-b061-11e4-8431-61168472df09.JPG)

![capture](https://cloud.githubusercontent.com/assets/3798589/6106510/5989e34a-b062-11e4-979b-268273c7ebcf.JPG)
![capture](https://cloud.githubusercontent.com/assets/3798589/6106476/fcae143e-b061-11e4-8374-d8fcec1e953b.JPG)

**Comment by naeemmuhammad** [comment]
https://github.com/libis/cagsandbox/commit/81c81a8e0fe75a19014d28f0ad5485be9a8feef0
