### ISSUE TITLE
mapping for "Actoren" needs to be added

### ISSUE THREAD

**Issue by roxannewyns** [libis/libisin#9]
exportHVL_actoren has to go to the Omeka type 'Collectie'. 
I send you the mail with the link to the display template 

![capture](https://cloud.githubusercontent.com/assets/3798589/6107504/bcea3206-b06b-11e4-8ea8-743569496323.JPG)

**Comment by naeemmuhammad** [comment]
d72fc23725aa92680e289b242fd66f0468255d00
